const FieldNames = {
    address: "Address",
    cabinetNumber: "Cabinet Number",
    careerStartYear: "Career Start Year",
    city: "City",
    complaints: "Complaints",
    conclusion: "Conclusion",
    dateOfBirth: "Date Of Birth",
    date: "Date",
    doctorFullName: "Full name doctor",
    diagnosis: "Diagnosis",
    email: "Email",
    firstName: "First Name",
    fullName: "Full name",
    houseNumber: "House Number",
    isApproved: "Is Approved",
    isActive: "Is Active",
    lastName: "Last Name",
    medicalServiceName: "Medical service",
    middleName: "Middle Name",
    office: "Office",
    officeAddress: "Office Address",
    officeNumber: "Office Number",
    patientFullName: "Full name patient",
    patientPhoneNumber: "Patient phone number",
    password: "Password",
    registryPhoneNumber: "Registry phone number",
    serviceName: "Service Name",
    specialization: "Specialization",
    specializationName: "Specialization Name",
    street: "Street",
    status: "Status",
    time: "Time",
    price: "Price",
    receptionistFullName: "Receptionist Full Name",
    categoryName: "Category Name",
    receptionistFullName: "Receptionist Full Name",
    recommendations: "Recommendations",
    patient: "Patient",
    doctor: "Doctor",
};

export default FieldNames;